"""
Django settings for FCfullstack project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS").split(",")


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.CSPMiddleware',  # Content Security Policy
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

#DATABASES["default"] = dj_database_url.parse("postgresql://fc_fullstack_user:Ii8qCwZ5KEvHpZi76SaXEBcFaF3dQNjh@dpg-d5lt91je5dus73e31nbg-a.ohio-postgres.render.com/fc_fullstack")

DATABASES = {
    'default': dj_database_url.parse(config('DATABASE_URL'))
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/



# Build paths inside the project like this: BASE_DIR / 'subdir'.


# ... other settings ...

STATIC_URL = 'static/'

# This tells Django where to copy all static files for production
# This is the line you were missing!
STATIC_ROOT = BASE_DIR / "staticfiles"

# Where Django looks for your custom CSS/JS
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",
]

# Media files settings
MEDIA_URL = '/media/'
MEDIA_ROOT = '/opt/render/project/src/media

# This is CRITICAL for Render to serve your Jazzmin styles correctly
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    # Title of the window
    "site_title": "Fourth Corner Admin",

    "site_header": "Fourth Corner",
    "site_logo": "image/apple-touch-icon.png", 
 
    "login_logo": "image/apple-touch-icon.png",


    "site_logo_classes": "img-fluid w-25", 
    
    # You can also add custom inline styles here specifically for the login logo
    "login_logo_classes": "img-fluid",

    # Relative path to a favicon for your site
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Welcome to FC Management",

    # Copyright on the footer
    "copyright": "Fourth Corner Ltd",
    "site_title": "FC Management",
    "site_header": "Fourth Corner",
    "site_brand": "FC MANAGEMENT",
    "site_logo": "image/Logo.webp", 
    "welcome_sign": "Welcome to FC Management",
    "copyright": "Fourth Corner Ltd",
    "show_ui_builder": True,
    "search_model": ["core.Post", "core.Job"],
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "core.Job": "fas fa-briefcase",
        "core.Post": "fas fa-newspaper",
    },
}



JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": True,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": True,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
    
}

# Security Settings - Content Security Policy (CSP)
# For production, consider using django-csp package for more granular control
# Install: pip install django-csp
# Then add 'csp' to INSTALLED_APPS and configure CSP_* settings

# Basic security headers (works with SecurityMiddleware)
if not DEBUG:
    # Content Security Policy - Basic configuration
    # Note: For full CSP support, install django-csp: pip install django-csp
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Additional security headers
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True  # Set to True if using HTTPS
    
    # CSP Headers (basic - for full CSP, use django-csp package)
    # These will be set via custom middleware or django-csp
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
else:
    # Development settings - less strict for debugging
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'  # Allow same-origin for development
