# Generated by Django 5.2.9 on 2026-01-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Show on Homepage'),
        ),
    ]
